development: &default
  adapter: postgresql
  database: TODO_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: uralfrkn
  password: 975365

test:
  <<: *default
  database: TODO_test
  username: uralfrkn
  password: 975365

production:
  <<: *default
  database: TODO_production

staging:
  <<: *default
  database: TODO_staging
  username: uralfrkn
  password: 975365
